### ISSUE TITLE
Illegal ANSYS cell type 'tetra35

### ISSUE THREAD

**Issue by jbs0645** [jiangzhongshi/bichon#8]
Hello,

 I met some problems when conducting the command introduced in the **README.md** file.
 I don`t know how to solve this kind of problem. Can you show me some hints? 

The conducted command:
`python ../python/format_utils.py bunny.off.h5 bunny.msh`

The err
```
Traceback (most recent call last):
  File "/home/test/SW/bichon/build/../python/format_utils.py", line 24, in <module>
    convert_cutet(sys.argv[1], sys.argv[2])
  File "/home/test/SW/bichon/build/../python/format_utils.py", line 18, in convert_cutet
    meshio.write(file2,
  File "/home/test/.local/lib/python3.9/site-packages/meshio/_helpers.py", line 188, in write
    return writer(filename, mesh, **kwargs)
  File "/home/test/.local/lib/python3.9/site-packages/meshio/ansys/_ansys.py", line 448, in write
    raise KeyError(
KeyError: "Illegal ANSYS cell type 'tetra35'. (legal: triangle, tetra, quad, hexahedron, pyramid, wedge)"
```

**Comment by jiangzhongshi** [comment]
Hi,

I cannot reproduce this issue right now. What is the version of meshio you are currently using?
From the error message, it seems that meshio is invoking the ansys format, while my intention is gmsh format, and then happen to share the same suffix (`.msh`).

 I suggest to try the following, 
in my script `format_utils.py", line 18, `, change from `meshio.write` to `meshio.gmsh.write` so it would be less ambiguous.

Let me know if it helps, so that I could also change the code to this way.

**Comment by jbs0645** [comment]
My `meshio` version is **5.3.4.** When I change the script of `format_utils.py` following your instruction, the code **works fine**, **thank you** for the concise help!
And I have another question: besides the `gmsh`, does there exist some other software to visualize the` .msh` result?

**Comment by jiangzhongshi** [comment]
Hi,

Glad it helps. Since we are dealing with high order unstructured meshes here (quadric tet35), as far as I know, gmsh, and vtk/paraview(it is [possible](https://www.kitware.com/modeling-arbitrary-order-lagrange-finite-elements-in-the-visualization-toolkit/) to convert to vtk, but I am not getting to it yet) are the common ones to visualize them. 

At the end of the day, visualizers mostly sample a linear triangle mesh and visualize. I usually have my own visualizer (through some [uniform sampling](https://github.com/jiangzhongshi/bichon/blob/main/python/vis_utils.py#L160), but undocumented).
